chapter03: 네트워크 계층
SSAMBBONG/cs-network pull request #18
Opened 2024-05-11 03:33 UTC by JiheunSeo

### 과제 수행 여부

- [X] 완료
- [ ] 미완료

### 사유 (미완료 시)
(이유를 간단히 설명해주세요)

---

### 관련 문서나 이슈
(관련된 문서나 이슈가 있다면 링크를 제공해주세요)

2024-05-11 14:43 UTC, MustSave requested changes

2024-05-11 14:43 UTC, MustSave commented on 서지흔/chapter03/README.md
> +    - 프레임의 페이로드로 데이터에 필드 명시 ← 프레임의 데이터 필드에는 상위계층에서 전달받거나 상위계층으로 전달해야 할 내용 명시되어야함
`프레임의 페이로드로 데이터에 필드 명시`
이 부분이 이해가 잘 되지 않아요

2024-05-11 14:43 UTC, MustSave commented on 서지흔/chapter03/README.md
> +  - 오늘날 네트워크에서는 대부분 경로 MTU 발견 지원 (DF플래그)
DF 플래그를 통해서 경로 MTU 발견을 한다고 생각될 수 있을 것 같아요

2024-05-11 14:43 UTC, MustSave commented on 서지흔/chapter03/README.md
> +- 네트워크 주소 : 무조건 비트0으로 시작 2^7 (0~127) 가능
이거는 A클래스에 한정된 내용

2024-05-11 14:43 UTC, MustSave commented on 서지흔/chapter03/README.md
> +- 호스트 주소 : 2^8 (0~ 255) 가능
이거는 C클래스 내용

2024-05-11 14:43 UTC, MustSave commented on 서지흔/chapter03/README.md
> +  - 호스트에게 동적 할당, 사용되지 않을 경우 회수, 할당받을때마다 다르 주소 받을 수 있음
```suggestion
  - 호스트에게 동적 할당, 사용되지 않을 경우 회수, 할당받을때마다 다른 주소 받을 수 있음
```

2024-05-11 14:43 UTC, MustSave commented on 서지흔/chapter03/README.md
> +- L3 스위치 장치와 유시
```suggestion
- L3 스위치 장치와 유사
```

2024-05-13 01:37 UTC, JiheunSeo commented on 서지흔/chapter03/README.md
> +- 호스트 주소 : 2^8 (0~ 255) 가능
수정했습니다!

2024-05-13 01:37 UTC, JiheunSeo commented on 서지흔/chapter03/README.md
> +- 네트워크 주소 : 무조건 비트0으로 시작 2^7 (0~127) 가능
수정했습니다!

2024-05-13 01:37 UTC, JiheunSeo commented on 서지흔/chapter03/README.md
> +  - 오늘날 네트워크에서는 대부분 경로 MTU 발견 지원 (DF플래그)
수정했습니다!

2024-05-13 01:40 UTC, JiheunSeo commented on 서지흔/chapter03/README.md
> +    - 프레임의 페이로드로 데이터에 필드 명시 ← 프레임의 데이터 필드에는 상위계층에서 전달받거나 상위계층으로 전달해야 할 내용 명시되어야함
`프레임의 페이로드로 데이터에 필드 명시`
데이터링크계층(하위계층)에서 네트워크 계층(상위계층)으로 전달하기 위해 프레임 내의 데이터 필드에 IPv4패킷이 명시됩니다.

내용 또한 수정했습니다 .

2024-05-13 04:48 UTC, simhani1 commented on 서지흔/chapter03/README.md
> +           - 그럼에도 불구하고 패키의 크기가 크다면? 폐기
```suggestion
           - 그럼에도 불구하고 패킷의 크기가 크다면? 폐기
```

2024-05-13 04:51 UTC, simhani1 commented on 서지흔/chapter03/README.md
> +         - 존재 이유 : 무의미한 패킷이 네트워크 상에 지속적으로 남아있는 것을 방지
네트워크에 떠돌아 다니는 패킷은 모두 무의미한 패킷인가요?

2024-05-13 04:51 UTC, simhani1 commented on 서지흔/chapter03/README.md
> +         - 존재 이유 : 무의미한 패킷이 네트워크 상에 지속적으로 남아있는 것을 방지
네트워크에 떠돌아 다니는 패킷은 모두 무의미한 패킷인가요?

2024-05-13 04:59 UTC, simhani1 commented on 서지흔/chapter03/README.md
> +  - 사설 IP만으로는 일반적인 인터넷 접속을 비롯한 외부 네트워크 간 통신 어려움
왜 사설 IP만으로는 외부 네트워크 간 통신이 어려운가요?

2024-05-13 05:02 UTC, simhani1 commented on 서지흔/chapter03/README.md
> +         - 2번 메시지에 대한 응답 전송 (브로드캐스트 전송) (얘는 왜 브로드 캐스트로 전송할까? 왜 애니캐스트가 아닐까?)
애니 캐스트는 가장 가까운 노드와 통신하는 방식이므로 적합하지 않을 것 같아요.
그리고 DHCP로 IP 주소 발급 요청을 보낸 호스트의 IP 주소가 부여되지 않은 상태라 브로드캐스트로 보내는 것 같아요.

2024-05-26 07:10 UTC, JiheunSeo commented on 서지흔/chapter03/README.md
> +         - 존재 이유 : 무의미한 패킷이 네트워크 상에 지속적으로 남아있는 것을 방지
수신지가 잘못설정되어 계속 네트워크상에서 떠도는 패킷은 무의미합니다.

2024-05-26 07:11 UTC, JiheunSeo commented on 서지흔/chapter03/README.md
> +  - 사설 IP만으로는 일반적인 인터넷 접속을 비롯한 외부 네트워크 간 통신 어려움
고유한 IP가 아니기 때문에 외부 네트워크에 겹치는 IP가 존재할 수 있습니다.

2024-05-26 07:12 UTC, JiheunSeo commented on 서지흔/chapter03/README.md
> +         - 2번 메시지에 대한 응답 전송 (브로드캐스트 전송) (얘는 왜 브로드 캐스트로 전송할까? 왜 애니캐스트가 아닐까?)
답변 감사합니다 땡큐

2024-05-26 15:05 UTC, MustSave approved these changes

2024-05-27 12:03 UTC, jijongkwon approved these changes

2024-05-27 13:10 UTC, merged