chapter03: 네트워크 계층
SSAMBBONG/cs-network pull request #19
Opened 2024-05-11 10:48 UTC by jijongkwon

### 과제 수행 여부

- [X] 완료
- [ ] 미완료

### 사유 (미완료 시)
(이유를 간단히 설명해주세요)

---

### 관련 문서나 이슈
(관련된 문서나 이슈가 있다면 링크를 제공해주세요)

2024-05-11 15:01 UTC, MustSave requested changes

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +## 1, 2 계층에 한계
```suggestion
## 1, 2 계층의 한계
```

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +   5. 그건 1,2계층에 있느 장비만으로느 불가능 !
```suggestion
   5. 그건 1,2계층에 있느 장비만으로는 불가능 !
```

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +IP 주소를 통해 MAC 주소르 알아내는 프로토콜
```suggestion
IP 주소를 통해 MAC 주소를 알아내는 프로토콜
```

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +라우터 위치 정보를 ARP 테이블에 저장해서 알아낼 수 있다
라우터 위치 정보가 뭔가요?

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +주소를 적게 할당할 수 있는데 IP주소가 많으면 할당 못하는 주소가 생김
IP주소 대신 호스트 수로 바꾸는게 어떤가요

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +서브네팅 : 서브넷 마스크를 이용해서 더 잘개 쪼개어서 사용하는 것
뭘 더 잘개 쪼개나요?

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +사설은 네트워크에서 사용하기 위한 IP 주소 ( 중복 가능 )
```suggestion
사설은 프라이빗 네트워크에서 사용하기 위한 IP 주소 ( 중복 가능 )
```

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +테이블에 최적 경로가 없다면, 디폴트 경로(0.0.0.0/0 모든 IP주소를 의미)로 감
디폴트 경로는 항상 0.0.0.0인가요?

2024-05-11 15:01 UTC, MustSave commented on 지종권/chapter03/README.md
> +AS : 단일한 라우팅 정책 하에 관리되는 IP 네트워크들의 집합
```suggestion
AS : 단일한 라우팅 정책 하에 관리되는 라우터들의 집합
```

2024-05-12 07:34 UTC, LEEJW1953 approved these changes

2024-05-12 08:06 UTC, jijongkwon commented on 지종권/chapter03/README.md
> +주소를 적게 할당할 수 있는데 IP주소가 많으면 할당 못하는 주소가 생김
수정했습니다

2024-05-12 08:11 UTC, jijongkwon commented on 지종권/chapter03/README.md
> +서브네팅 : 서브넷 마스크를 이용해서 더 잘개 쪼개어서 사용하는 것
클래스 입니다. 수정했습니다

2024-05-12 08:11 UTC, jijongkwon commented on 지종권/chapter03/README.md
> +라우터 위치 정보를 ARP 테이블에 저장해서 알아낼 수 있다
MAC 주소입니다. 수정했습니다

2024-05-12 08:14 UTC, jijongkwon commented on 지종권/chapter03/README.md
> +테이블에 최적 경로가 없다면, 디폴트 경로(0.0.0.0/0 모든 IP주소를 의미)로 감
명시적인 라우트가 없는 트래픽이라면, 그렇습니다

2024-05-12 09:09 UTC, MustSave commented on 지종권/chapter03/README.md
> +테이블에 최적 경로가 없다면, 디폴트 경로(0.0.0.0/0 모든 IP주소를 의미)로 감
0.0.0.0이 모든 IP 주소를 의미한다고 써있는데 그렇다면 브로드캐스트 하는 걸까요?

2024-05-13 05:10 UTC, simhani1 commented on 지종권/chapter03/README.md
> +그래도 아직까지는 ipv4를 많이 사용한다
왜 아직까지는 IPv4를 많이 사용하나요?

2024-05-13 05:11 UTC, simhani1 commented on 지종권/chapter03/README.md
> +근데 이렇게 나눠도 분명이 낭비되는 공간이 있을 것이다
```suggestion
근데 이렇게 나눠도 분명히 낭비되는 공간이 있을 것이다
```

2024-05-13 05:12 UTC, simhani1 commented on 지종권/chapter03/README.md
> +공인은 고유한 IP 주소
공인 IP주소라고 해야 정확한 것 같아요

2024-05-13 05:16 UTC, jijongkwon commented on 지종권/chapter03/README.md
> +그래도 아직까지는 ipv4를 많이 사용한다
아직까지는 ipv6보다 ipv4를 호환하는 장치나 소프트웨어가 더 많기 때문입니다.

2024-05-26 07:12 UTC, JiheunSeo approved these changes

2024-05-26 15:02 UTC, MustSave approved these changes

2024-05-27 00:03 UTC, merged