chapter04: 전송 계층
SSAMBBONG/cs-network pull request #27
Opened 2024-05-26 13:53 UTC by jijongkwon

### 과제 수행 여부

- [X] 완료
- [ ] 미완료

### 사유 (미완료 시)
(이유를 간단히 설명해주세요)

---

### 관련 문서나 이슈
(관련된 문서나 이슈가 있다면 링크를 제공해주세요)

2024-05-26 15:49 UTC, MustSave requested changes

2024-05-26 15:49 UTC, MustSave commented on 지종권/chapter04/README.md
> +  - 송신자 인증 없음
송신자 인증은 책이랑 인터넷 찾아봐도 안보이는데 혹시 ACK를 말하는거?

2024-05-26 15:49 UTC, MustSave commented on 지종권/chapter04/README.md
> +사진처럼 보내다가 응답이 오면
`응답이 오면` 보다는 응답을 받지 못해 타임아웃이 발생한다면이 더 맞지 않을까

2024-05-26 15:49 UTC, MustSave commented on 지종권/chapter04/README.md
> +모든 세그먼트를 재전송해야 한다는 단점이 있음
모든 세그먼트 보다는 오류가 있는 세그먼트 이후의 모든 세그먼트가 의미상 맞을듯

2024-05-26 15:49 UTC, MustSave commented on 지종권/chapter04/README.md
> +세 번의 중독된 ACK 세그먼트를 수신하면 혼잡 회피를 수행하는 알고리즘
오타는 안잡으려 했는데 중독은 좀 ㅋㅋㅋ

2024-05-30 08:17 UTC, jijongkwon commented on 지종권/chapter04/README.md
> +  - 송신자 인증 없음
넵 ack 입니다 ~

2024-05-30 08:17 UTC, jijongkwon commented on 지종권/chapter04/README.md
> +사진처럼 보내다가 응답이 오면
수정했습니다~

2024-05-30 08:17 UTC, jijongkwon commented on 지종권/chapter04/README.md
> +모든 세그먼트를 재전송해야 한다는 단점이 있음
수정했습니다~

2024-05-30 08:17 UTC, jijongkwon commented on 지종권/chapter04/README.md
> +세 번의 중독된 ACK 세그먼트를 수신하면 혼잡 회피를 수행하는 알고리즘
수정했습니다~

2024-05-30 08:27 UTC, simhani1 approved these changes

2024-05-30 08:31 UTC, MustSave approved these changes

2024-05-30 08:37 UTC, merged