Chapter 02: 물리 계층과 데이터 링크 계층
SSAMBBONG/cs-network pull request #6
Opened 2024-05-07 08:55 UTC by JiheunSeo

### 과제 수행 여부

- [X] 완료
- [ ] 미완료

### 사유 (미완료 시)
(이유를 간단히 설명해주세요)

---

### 관련 문서나 이슈
(관련된 문서나 이슈가 있다면 링크를 제공해주세요)

2024-05-07 14:55 UTC, simhani1 approved these changes

2024-05-08 00:35 UTC, MustSave requested changes
+이미지 추가 요청

2024-05-08 00:35 UTC, MustSave commented on 서지흔/chapter02/README.md
> +    - 광섬위케이블
```suggestion
    - 광섬유케이블
```

2024-05-08 00:35 UTC, MustSave commented on 서지흔/chapter02/README.md
> +- 차폐 : 노이즈를 방지하기 위해 구리선 줍ㄴ을 철사(브레이드실드), 포일(포일실드)로 감쌈
```suggestion
- 차폐 : 노이즈를 방지하기 위해 구리선을 철사(브레이드실드), 포일(포일실드)로 감쌈
```

2024-05-08 00:35 UTC, MustSave commented on 서지흔/chapter02/README.md
> +  - 코어 지름 : 8~10mm (멀티모드 광섬유 케이블 보다 작음) → 빛이 이동할 수 있는 경로 많음 → 빛 이동경로 하나 이상 갖기 힘들고 mode가 single이라 표현
```suggestion
  - 코어 지름 : 8~10mm (멀티모드 광섬유 케이블 보다 작음) → 빛이 이동할 수 있는 경로 적음 → 빛 이동경로 하나 이상 갖기 힘들고 mode가 single이라 표현
```

2024-05-08 00:35 UTC, MustSave commented on 서지흔/chapter02/README.md
> +  - 허브를 통해 신호 전달받은 호스트는 데이터링크 계층에서 패킷 MAC주소 확인 후 자신과 관련없는 주소 폐기
```suggestion
  - 허브를 통해 신호 전달받은 호스트는 데이터링크 계층에서 프레임 MAC주소 확인 후 자신과 관련없는 프레임 폐기
```

2024-05-08 00:35 UTC, MustSave commented on 서지흔/chapter02/README.md
> +1. 플러딩 : 스위치는 마치 허브처럼 송신지 포트를 제외한 모든 포트로 프레임을 전송
플러딩 조건 추가하는게 좋을듯?

2024-05-08 01:39 UTC, MustSave approved these changes

2024-05-08 02:02 UTC, merged